### PR TITLE
Bubble up return -1 to raise exception on parse failure

### PR DESCRIPTION
**Pull request by crystaljg**
## Description
Simply `exit(0)`ing upon an unmatched version made it such that I couldn't simply catch a filing that failed to parse and move on. This PR causes the `unmatched version` error to `return -1` up through its stack until I can raise an exception in Python.

This seems to work in principle, but I have the following concerns:
* Is raising just an `Exception` sufficient since the actual error is being printed to `stderr` beforehand?
* Is there anything I need to do re: cleaning up memory? I raise the exception in `client.py` after the `# Free memory and file descriptors`, but unsure if I need to do anything else.
* I welcome any other suggestions!!

## Link to Jira Ticket
Relates to [DENG-129](https://actblue.atlassian.net/browse/DENG-129?atlOrigin=eyJpIjoiNWUyYTgzYjZhZWM0NGVkNDljYzRjOWJhYmE4ZmI0OGYiLCJwIjoiaiJ9)

## Test Steps
I also made a little test script to make sure this gets caught.
```
from fastfec import FastFEC
import smart_open
import logging

if __name__ == "__main__":
    filing_id = 1613679 # broken
    # filing_id = 1613811 # works
    
    # import os
    # _TEST_FOLDER = os.path.dirname(__file__)
    # filing_id=1613679
    # fec_source_url = os.path.join(_TEST_FOLDER, "1613679_malformed.fec")
    fec_source_url = f"http://docquery.fec.gov/dcdev/posted/{filing_id}.fec"


    with smart_open.open(
        fec_source_url,
        "rb",
        transport_params={"headers": {"User-Agent": "Mozilla/5.0"}},
    ) as f:
        with FastFEC() as fastfec:
            try:
                logging.info(
                    f"Extracting from {fec_source_url} to s3 for filing_id {filing_id}"
                )
                fastfec.parse_as_files(
                    f, 'output/', include_filing_id=str(filing_id)
                )

            except Exception as e:
                logging.error(f"Failed to parse filing_id {filing_id}. Skipping. {e}")
```
which returns
```
FastFEC % python python/src/fastfec/test.py
Error: Unmatched for version 8.4 and form type F3Z1
ERROR:root:Failed to parse filing_id 1613679. Skipping. FastFEC failed to parse.
```

### CODE REVIEW

**Comment by james-clemer-actblue** [comment]
I have some concerns about changing the application-semantics as part of a library change.

My concern goes like this:
- if we can't merge back into wapo/fastfec it will be more difficult to contribute to that repo and to pick up bugfixes they make in this repo
- it'd be nice to be able to help others' use of the library functionality

One solution might go something like:
- conditionally return/exit based on if you're compiling the library/application

**Comment by james-clemer-actblue** [comment]
We talked synchronously about it and landed on something like:
- this approach is good as it unblocks the actual ticket at hand
- this approach could maybe benefit from different return values (I like `0` for success and `1` for failure, but there's plenty of ways to do it) and likely benefit from return `CONSTANTS`
- in the future it'd be nice to flesh this out such that instead of `exit(1)`ing, we `return 1;` and respond up the stack until we get to `main.c` so that we can PR something along these lines to washingtonpost/FastFEC
👍

**Comment by crystaljg** [comment]
A note for future me when I go back to work on this: catching the exception doesn't prevent `writer.c` from writing the files, so will need to dig deeper the flow and maybe do a test about it

**Comment by james-clemer-actblue** [comment]
> A note for future me when I go back to work on this: catching the exception doesn't prevent `writer.c` from writing the files, so will need to dig deeper the flow and maybe do a test to make sure files don't get written

Half-Baked Hunch: I suspect that this is because we didn't add the chain of `return`s up the stack. So, we return at the error-site, but then can continue, because we didn't exit the outer process.

**Review by james-clemer-actblue — APPROVED** [review]
Understanding that this is a kludge to get back to the ticket at hand, 🚢 🇮🇹 

Thanks for talking with me yesterday about future work to get this + other changes into the original trunk repo

**Comment by crystaljg** [comment]
woop i appreciate it! but I am gonna go and fix this today and then re ask for a review, sorry. i will remove you as a reviewer for now

**Comment by crystaljg** [comment]
Made a ticket to make changes that would allow this to get submitted to wapo: https://actblue.atlassian.net/browse/DENG-148?atlOrigin=eyJpIjoiZmZjNjFiM2U2ZDkyNGM5NTlkMjFjOTdkNDI5NDhlNWUiLCJwIjoiaiJ9

**Pull request merged**
